### ISSUE TITLE
兄弟你好，麻烦看一下

### ISSUE THREAD

**Issue by ghost** [bbs3223474/HANA16_Renpy#4]
![image](https://user-images.githubusercontent.com/70136204/96389438-34243000-11e2-11eb-9b30-ad9737b62b0e.png)
大佬这个soga和nginx是怎么实现的呢？stream转发后怎么搞呢？我的面板对接的端口是53784，但是soga还是占用了80和443，无解
![image](https://user-images.githubusercontent.com/70136204/96389488-751c4480-11e2-11eb-9e81-13d480eb2f2a.png)
![image](https://user-images.githubusercontent.com/70136204/96389511-95e49a00-11e2-11eb-97e9-73537c60c22b.png)

**Comment by bbs3223474** [comment]
Stream转发后，将用于soga的域名的.conf文件中的443端口相关所有字段全部删除，只保留80端口相关的（与未进行SSL签名的样式相同）。
前端按照如下格式设置：“soga域名;port=443#实际需要soga监听的端口号”
重启Nginx和Soga，不报错就证明成功。
